server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nft_marketplace?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none # Deaktiviert die automatische Schema-Generierung
    show-sql: false # SQL-Statements nicht anzeigen
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect